# Generated by Django 4.1.1 on 2022-09-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': ('Base Information Header',),
                'verbose_name_plural': 'Base Information Headers',
                'ordering': ('pk', 'title', 'code', 'is_active'),
            },
        ),
        migrations.CreateModel(
            name='BaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_information.header', verbose_name='header')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_information.baseinformation', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Base Information',
                'verbose_name_plural': 'Base Information',
                'ordering': ('pk', 'header', 'value', 'code', 'is_active'),
            },
        ),
    ]
